//! Contract export: golden file, determinism, `cue vet` against the
//! meta-schema, declaration checks, and config-file profiles.

mod common;

use std::path::Path;
use std::time::Duration;

use common::{cue_vet, Gateway};
use docuconf::figment::providers::{Format, Toml};
use docuconf::figment::Figment;
use docuconf::url::Url;
use docuconf::{Code, Docuconf, Error, Meta, Secret};
use serde::Deserialize;

const GOLDEN: &str = "tests/golden/gateway.cue";

#[test]
fn export_matches_golden() {
    let out = docuconf::export::<Gateway>(&Meta::new("gateway")).unwrap();
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(GOLDEN);
    if std::env::var_os("UPDATE_GOLDEN").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &out).unwrap();
    }
    let want = std::fs::read_to_string(&path).unwrap();
    assert_eq!(
        want, out,
        "export changed; run UPDATE_GOLDEN=1 cargo test --test export to accept"
    );
    let again = docuconf::export::<Gateway>(&Meta::new("gateway")).unwrap();
    assert_eq!(out, again, "export must be deterministic");
}

#[test]
fn export_header_and_metadata() {
    let out = docuconf::export::<Gateway>(&Meta::new("gateway-api").app_version("1.2.3")).unwrap();
    assert!(out.starts_with(
        "// Code generated by docuconf. DO NOT EDIT.\npackage gateway_api\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & {\n"
    ));
    assert!(out.contains("appVersion: \"1.2.3\""));
    assert!(out.contains("language: \"rust\""));
    let err = docuconf::export::<Gateway>(&Meta::new("Gateway")).unwrap_err();
    assert!(err.to_string().contains("DNS label"), "{err}");
}

// ---------------------------------------------------------------------------
// cue vet

#[test]
fn export_passes_cue_vet() {
    let out = docuconf::export::<Gateway>(&Meta::new("gateway").app_version("1.2.3")).unwrap();
    let Some(res) = cue_vet(&out) else { return };
    res.unwrap_or_else(|e| panic!("cue vet failed:\n{e}\n{out}"));

    // A broken contract is rejected, so this test can fail.
    let bad = out.replacen("type:        \"int\"", "type:        \"integer\"", 1);
    assert_ne!(bad, out);
    assert!(cue_vet(&bad).unwrap().is_err());
}

// ---------------------------------------------------------------------------
// Declaration checks

#[test]
fn declaration_errors() {
    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Bad {
        /// Lower-case names are not environment variable names.
        #[docuconf(env = "lower")]
        lower: String,
        /// A required variable cannot have a default.
        #[docuconf(required, default = 1)]
        both: i32,
        /// Defaults must satisfy their own constraints.
        #[docuconf(default = 0, min = 1)]
        port: u16,
        /// Patterns must be RE2.
        #[docuconf(pattern = "(?=x)")]
        look: String,
        /// min does not apply to strings.
        #[docuconf(min = 1)]
        str_min: String,
        /// Secrets have no defaults.
        #[docuconf(default = "x")]
        token: Secret<String>,
        no_docs: String,
        /// Durations need humantime_serde.
        #[docuconf(default = "5s")]
        timeout: Duration,
        /// A file input under a reserved directory.
        #[docuconf(path = "/etc/ca.pem")]
        ca: docuconf::CaBundle,
        /// Watching is not implemented.
        #[docuconf(path = "/etc/app/notes/notes.txt", reload = "watch")]
        notes: docuconf::TextFile,
        /// The password of a keystore must be a secret.
        #[docuconf(path = "/etc/app/ks/ks.p12", password_var = "LOWER_NOT_SECRET")]
        ks: docuconf::Keystore,
        /// Not secret, so not a keystore password.
        lower_not_secret: String,
    }
    let err = docuconf::check_declaration::<Bad>().unwrap_err();
    let all = err.problems.join("\n");
    for want in [
        "lower (Bad.lower): variable name must match",
        "BOTH (Bad.both): a required variable must not have a default",
        "PORT (Bad.port): default 0 is below min 1",
        "LOOK (Bad.look): pattern \"(?=x)\" is not valid RE2",
        "STR_MIN (Bad.str_min): attribute `min` does not apply to a string variable",
        "TOKEN (Bad.token): a secret variable must not have a default",
        "NO_DOCS (Bad.no_docs): needs a description",
        "TIMEOUT (Bad.timeout): a Duration field needs #[serde(with = \"docuconf::humantime_serde\")]",
        "file input ca (Bad.ca): would be mounted at /etc",
        "file input notes (Bad.notes): reload = \"watch\" is not implemented",
        "file input ks (Bad.ks): password_var LOWER_NOT_SECRET must be a secret variable",
    ] {
        assert!(all.contains(want), "missing {want:?} in\n{all}");
    }

    // Loading reports the declaration error, not violations.
    let e = docuconf::Loader::<Bad>::new()
        .env(Vec::<(String, String)>::new())
        .load()
        .unwrap_err();
    assert!(matches!(e, Error::Declaration(_)));
}

#[test]
fn mount_collisions_and_path_env_rules() {
    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Bad {
        /// First file in a shared directory.
        #[docuconf(path = "/etc/app/shared/a.txt", path_env = "A_FILE")]
        a: docuconf::TextFile,
        /// Second file in a shared directory.
        #[docuconf(path = "/etc/app/shared/b.txt", path_env = "A_FILE")]
        b: docuconf::TextFile,
        /// A path that is not normalised.
        #[docuconf(path = "/etc/app/../x.txt")]
        c: docuconf::TextFile,
        /// Also the name of a variable.
        a_file: Option<String>,
    }
    let err = docuconf::check_declaration::<Bad>().unwrap_err();
    let all = err.problems.join("\n");
    for want in [
        "file input b (Bad.b): shares mount directory /etc/app/shared with file input a",
        "path_env A_FILE must not also be a declared variable",
        "path_env A_FILE is also used by file input a",
        "file input c (Bad.c): path \"/etc/app/../x.txt\" must be absolute and normalised",
    ] {
        assert!(all.contains(want), "missing {want:?} in\n{all}");
    }
}

// ---------------------------------------------------------------------------
// Config files and profiles (SPEC §4.4)

#[derive(Debug, Deserialize, Docuconf)]
#[docuconf(prefix = "APP_")]
#[allow(dead_code)]
struct Svc {
    /// Deployment profile: production or staging.
    #[docuconf(default = "production")]
    profile: String,
    /// Warehouse API base URL.
    #[docuconf(schemes("https"))]
    warehouse_api: Url,
    /// Number of background workers.
    #[docuconf(default = 4, min = 1)]
    workers: u32,
    /// Payment provider API key.
    api_key: Secret<String>,
}

const APP_TOML: &str = r#"
[default]
workers = 8

[production]
warehouse_api = "https://warehouse.internal"

[staging]
warehouse_api = "https://warehouse.staging.internal"
workers = 2
"#;

fn svc_loader() -> docuconf::Loader<Svc> {
    docuconf::Loader::new()
        .figment(Figment::from(Toml::string(APP_TOML).nested()))
        .profiles("APP_PROFILE", "production")
        .termination_log(false)
}

#[test]
fn profiles_are_exported() {
    let out = svc_loader().export(&Meta::new("svc")).unwrap();
    assert!(
        out.contains(
            "\tprofiles: {\n\t\tselector: \"APP_PROFILE\"\n\t\tdefault:  \"production\"\n\t\tdefaults: {\n\t\t\tproduction: {\n\t\t\t\tAPP_WAREHOUSE_API: \"https://warehouse.internal\"\n\t\t\t}\n\t\t\tstaging: {\n\t\t\t\tAPP_WAREHOUSE_API: \"https://warehouse.staging.internal\"\n\t\t\t\tAPP_WORKERS:       2\n\t\t\t}\n\t\t}\n\t}\n"
        ),
        "{out}"
    );
    // The base file's value is the default.
    assert!(
        out.contains("APP_WORKERS: {\n\t\t\ttype:        \"int\"\n\t\t\tdescription: \"Number of background workers\"\n\t\t\tdefault:     8\n"),
        "{out}"
    );
    if let Some(res) = cue_vet(&out) {
        res.unwrap_or_else(|e| panic!("cue vet failed:\n{e}\n{out}"));
    }
}

#[test]
fn profiles_select_values_and_env_wins() {
    let base = [("APP_API_KEY", "k")];
    let s = svc_loader().env(base).load().unwrap();
    assert_eq!(s.warehouse_api.as_str(), "https://warehouse.internal/");
    assert_eq!(s.workers, 8);

    let s = svc_loader()
        .env([("APP_API_KEY", "k"), ("APP_PROFILE", "staging")])
        .load()
        .unwrap();
    assert_eq!(s.profile, "staging");
    assert_eq!(
        s.warehouse_api.as_str(),
        "https://warehouse.staging.internal/"
    );
    assert_eq!(s.workers, 2);

    let s = svc_loader()
        .env([
            ("APP_API_KEY", "k"),
            ("APP_PROFILE", "staging"),
            ("APP_WORKERS", "3"),
        ])
        .load()
        .unwrap();
    assert_eq!(
        s.workers, 3,
        "the platform's variables override file values"
    );

    // A profile with no file makes the platform responsible.
    let err = svc_loader()
        .env([("APP_API_KEY", "k"), ("APP_PROFILE", "dev")])
        .load()
        .unwrap_err();
    assert_eq!(
        err.violations()
            .iter()
            .map(|v| (v.input.as_str(), v.code))
            .collect::<Vec<_>>(),
        [("APP_WAREHOUSE_API", Code::MissingRequired)]
    );
}

#[test]
fn bad_file_values_fail_export_and_load() {
    let toml = "[default]\nworkers = 0\n[production]\nwarehouse_api = \"http://plain\"\n";
    let loader = || {
        docuconf::Loader::<Svc>::new()
            .figment(Figment::from(Toml::string(toml).nested()))
            .profiles("APP_PROFILE", "production")
            .termination_log(false)
    };
    let err = loader().export(&Meta::new("svc")).unwrap_err();
    let all = err.problems.join("\n");
    assert!(
        all.contains(
            "APP_WORKERS (Svc.workers): config file value (profile default) 0 is below min 1"
        ),
        "{all}"
    );
    assert!(all.contains("APP_WAREHOUSE_API (Svc.warehouse_api): config file value (profile production) \"http://plain\" has scheme http"), "{all}");

    let err = loader().env([("APP_API_KEY", "k")]).load().unwrap_err();
    let mut codes: Vec<_> = err
        .violations()
        .iter()
        .map(|v| (v.input.as_str(), v.code))
        .collect();
    codes.sort();
    assert_eq!(
        codes,
        [
            ("APP_WAREHOUSE_API", Code::InvalidScheme),
            ("APP_WORKERS", Code::OutOfRange)
        ]
    );
}

#[test]
fn secrets_must_not_be_in_config_files() {
    let toml = "[default]\napi_key = \"sk_live_123\"\nwarehouse_api = \"https://w\"\n";
    let err = docuconf::Loader::<Svc>::new()
        .figment(Figment::from(Toml::string(toml).nested()))
        .profiles("APP_PROFILE", "production")
        .export(&Meta::new("svc"))
        .unwrap_err();
    let all = err.problems.join("\n");
    assert!(
        all.contains("APP_API_KEY (Svc.api_key): a secret must not have a value in a config file"),
        "{all}"
    );
    assert!(!all.contains("sk_live_123"));
}

#[test]
fn profiles_need_a_selector() {
    let err = docuconf::Loader::<Svc>::new()
        .figment(Figment::from(Toml::string(APP_TOML).nested()))
        .export(&Meta::new("svc"))
        .unwrap_err();
    assert!(err.to_string().contains("call Loader::profiles"), "{err}");

    let err = docuconf::Loader::<Svc>::new()
        .figment(Figment::from(Toml::string(APP_TOML).nested()))
        .profiles("PROFILE", "production")
        .export(&Meta::new("svc"))
        .unwrap_err();
    assert!(
        err.to_string()
            .contains("profile selector PROFILE must be a declared variable"),
        "{err}"
    );
}

#[test]
fn global_values_override_every_profile() {
    let toml = "[global]\nworkers = 6\n[staging]\nworkers = 2\nwarehouse_api = \"https://s\"\n";
    let loader = || {
        docuconf::Loader::<Svc>::new()
            .figment(Figment::from(Toml::string(toml).nested()))
            .profiles("APP_PROFILE", "production")
            .termination_log(false)
    };
    let out = loader().export(&Meta::new("svc")).unwrap();
    assert!(out.contains("default:     6"), "{out}");
    assert!(!out.contains("APP_WORKERS:       2"), "{out}");
    let s = loader()
        .env([("APP_API_KEY", "k"), ("APP_PROFILE", "staging")])
        .load()
        .unwrap();
    assert_eq!(s.workers, 6, "as figment does, and as the contract says");
}
