//! Contract export: golden file, determinism, `cue vet` against the
//! meta-schema, declaration checks, and config-file profiles.
// These tests use the TLS and keystore file inputs (default features).
#![cfg(all(feature = "tls", feature = "keystore"))]

mod common;

use std::path::Path;

use common::{cue_vet, Gateway};
use docuconf::figment::providers::{Format, Toml};
use docuconf::figment::Figment;
use docuconf::url::Url;
use docuconf::{Code, Docuconf, Error, Meta, Secret};
use serde::Deserialize;

const GOLDEN: &str = "tests/golden/gateway.cue";

#[test]
fn export_matches_golden() {
    let out = docuconf::export::<Gateway>(&Meta::new("gateway")).unwrap();
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(GOLDEN);
    if std::env::var_os("UPDATE_GOLDEN").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &out).unwrap();
    }
    let want = std::fs::read_to_string(&path).unwrap();
    assert_eq!(
        want, out,
        "export changed; run UPDATE_GOLDEN=1 cargo test --test export to accept"
    );
    let again = docuconf::export::<Gateway>(&Meta::new("gateway")).unwrap();
    assert_eq!(out, again, "export must be deterministic");
}

#[test]
fn export_header_and_metadata() {
    let out = docuconf::export::<Gateway>(&Meta::new("gateway-api").app_version("1.2.3")).unwrap();
    assert!(out.starts_with(
        "// Code generated by docuconf. DO NOT EDIT.\npackage gateway_api\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & {\n"
    ));
    assert!(out.contains("appVersion: \"1.2.3\""));
    assert!(out.contains("language: \"rust\""));
    let err = docuconf::export::<Gateway>(&Meta::new("Gateway")).unwrap_err();
    assert!(err.to_string().contains("DNS label"), "{err}");
}

// ---------------------------------------------------------------------------
// cue vet

#[test]
fn export_passes_cue_vet() {
    let out = docuconf::export::<Gateway>(&Meta::new("gateway").app_version("1.2.3")).unwrap();
    let Some(res) = cue_vet(&out) else { return };
    res.unwrap_or_else(|e| panic!("cue vet failed:\n{e}\n{out}"));

    // A broken contract is rejected, so this test can fail.
    let bad = out.replacen("type:        \"int\"", "type:        \"integer\"", 1);
    assert_ne!(bad, out);
    assert!(cue_vet(&bad).unwrap().is_err());
}

// ---------------------------------------------------------------------------
// Declaration checks

#[test]
fn declaration_errors() {
    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Bad {
        /// Lower-case names are not environment variable names.
        #[docuconf(env = "lower")]
        lower: String,
        /// Patterns must be RE2.
        #[docuconf(pattern = "(?=x)")]
        look: String,
        /// min does not apply to strings.
        #[docuconf(min = 1)]
        str_min: String,
        /// A file input under a reserved directory.
        #[docuconf(path = "/etc/ca.pem")]
        ca: docuconf::CaBundle,
        /// Watching is not implemented.
        #[docuconf(path = "/etc/app/notes/notes.txt", reload = "watch")]
        notes: docuconf::TextFile,
        /// The password of a keystore must be a secret.
        #[docuconf(path = "/etc/app/ks/ks.p12", password_var = "LOWER_NOT_SECRET")]
        ks: docuconf::Keystore,
        /// Not secret, so not a keystore password.
        lower_not_secret: String,
        /// Item bounds only apply to int lists.
        #[docuconf(item_min = 1)]
        names: Vec<String>,
        /// Item bounds must leave a range after narrowing to the item type.
        #[docuconf(item_min = 300)]
        ids: Vec<u8>,
    }
    // Mistakes visible in the attributes and the field type (a missing
    // description, a default that breaks its bounds or its type, a secret
    // or required variable with a default, a Duration without
    // humantime_serde) are compile errors; see src/compile_errors.rs.
    // These need the whole declaration.
    let err = docuconf::check_declaration::<Bad>().unwrap_err();
    let all = err.problems.join("\n");
    for want in [
        "lower (Bad.lower): variable name must match",
        "LOOK (Bad.look): pattern \"(?=x)\" is not valid RE2",
        "STR_MIN (Bad.str_min): attribute `min` does not apply to a string variable",
        "file input ca (Bad.ca): would be mounted at /etc",
        "file input notes (Bad.notes): reload = \"watch\" is not implemented",
        "file input ks (Bad.ks): password_var LOWER_NOT_SECRET must be a secret variable",
        "NAMES (Bad.names): attribute `item_min` does not apply to a list of strings variable",
        "IDS (Bad.ids): item_min 300 is above item_max 255",
    ] {
        assert!(all.contains(want), "missing {want:?} in\n{all}");
    }

    // Loading reports the declaration error, not violations.
    let e = docuconf::Loader::<Bad>::new()
        .env(Vec::<(String, String)>::new())
        .load()
        .unwrap_err();
    assert!(matches!(e, Error::Declaration(_)));
}

#[test]
fn list_item_bounds_are_exported_within_the_item_type() {
    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Lists {
        /// Narrow items get their type's range.
        a: Vec<u16>,
        /// Signed 32-bit items.
        b: Vec<i32>,
        /// User bounds inside the type's range.
        #[docuconf(item_min = -5, item_max = 100)]
        c: Vec<i8>,
        /// User bounds wider than the type are narrowed to it.
        #[docuconf(item_min = -1000, item_max = 1000)]
        d: Vec<u8>,
        /// 64-bit items have no implicit bounds.
        e: Vec<i64>,
    }
    let out = docuconf::export::<Lists>(&Meta::new("lists")).unwrap();
    let block = |name: &str| {
        let start = out.find(&format!("\t\t{name}: {{")).unwrap();
        let end = start + out[start..].find("\t\t}").unwrap();
        out[start..end].to_string()
    };
    assert!(
        block("A").contains("itemMin:     0\n") && block("A").contains("itemMax:     65535\n"),
        "{out}"
    );
    assert!(
        block("B").contains("itemMin:     -2147483648\n")
            && block("B").contains("itemMax:     2147483647\n"),
        "{out}"
    );
    assert!(
        block("C").contains("itemMin:     -5\n") && block("C").contains("itemMax:     100\n"),
        "{out}"
    );
    assert!(
        block("D").contains("itemMin:     0\n") && block("D").contains("itemMax:     255\n"),
        "{out}"
    );
    assert!(
        !block("E").contains("itemMin") && !block("E").contains("itemMax"),
        "{out}"
    );
    if let Some(res) = cue_vet(&out) {
        res.unwrap_or_else(|e| panic!("cue vet failed:\n{e}\n{out}"));
    }
}

#[test]
fn mount_collisions_and_path_env_rules() {
    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Bad {
        /// First file in a shared directory.
        #[docuconf(path = "/etc/app/shared/a.txt", path_env = "A_FILE")]
        a: docuconf::TextFile,
        /// Second file in a shared directory.
        #[docuconf(path = "/etc/app/shared/b.txt", path_env = "A_FILE")]
        b: docuconf::TextFile,
        /// A path that is not normalised.
        #[docuconf(path = "/etc/app/../x.txt")]
        c: docuconf::TextFile,
        /// Also the name of a variable.
        a_file: Option<String>,
    }
    let err = docuconf::check_declaration::<Bad>().unwrap_err();
    let all = err.problems.join("\n");
    for want in [
        "file input b (Bad.b): shares mount directory /etc/app/shared with file input a",
        "path_env A_FILE must not also be a declared variable",
        "path_env A_FILE is also used by file input a",
        "file input c (Bad.c): path \"/etc/app/../x.txt\" must be absolute and normalised",
    ] {
        assert!(all.contains(want), "missing {want:?} in\n{all}");
    }
}

// ---------------------------------------------------------------------------
// Config files and profiles (SPEC §4.4)

#[derive(Debug, Deserialize, Docuconf)]
#[docuconf(prefix = "APP_")]
#[allow(dead_code)]
struct Svc {
    /// Deployment profile: production or staging.
    #[docuconf(default = "production")]
    profile: String,
    /// Warehouse API base URL.
    #[docuconf(schemes("https"))]
    warehouse_api: Url,
    /// Number of background workers.
    #[docuconf(default = 4, min = 1)]
    workers: u32,
    /// Payment provider API key.
    api_key: Secret<String>,
}

const APP_TOML: &str = r#"
[default]
workers = 8

[production]
warehouse_api = "https://warehouse.internal"

[staging]
warehouse_api = "https://warehouse.staging.internal"
workers = 2
"#;

fn svc_loader() -> docuconf::Loader<Svc> {
    docuconf::Loader::new()
        .figment(Figment::from(Toml::string(APP_TOML).nested()))
        .profiles("APP_PROFILE", "production")
        .termination_log(false)
}

#[test]
fn profiles_are_exported() {
    let out = svc_loader().export(&Meta::new("svc")).unwrap();
    assert!(
        out.contains(
            "\tprofiles: {\n\t\tselector: \"APP_PROFILE\"\n\t\tdefault:  \"production\"\n\t\tdefaults: {\n\t\t\tproduction: {\n\t\t\t\tAPP_WAREHOUSE_API: \"https://warehouse.internal\"\n\t\t\t}\n\t\t\tstaging: {\n\t\t\t\tAPP_WAREHOUSE_API: \"https://warehouse.staging.internal\"\n\t\t\t\tAPP_WORKERS:       2\n\t\t\t}\n\t\t}\n\t}\n"
        ),
        "{out}"
    );
    // The base file's value is the default.
    assert!(
        out.contains("APP_WORKERS: {\n\t\t\ttype:        \"int\"\n\t\t\tdescription: \"Number of background workers\"\n\t\t\tdefault:     8\n"),
        "{out}"
    );
    if let Some(res) = cue_vet(&out) {
        res.unwrap_or_else(|e| panic!("cue vet failed:\n{e}\n{out}"));
    }
}

#[test]
fn profiles_select_values_and_env_wins() {
    let base = [("APP_API_KEY", "k")];
    let s = svc_loader().env(base).load().unwrap();
    assert_eq!(s.warehouse_api.as_str(), "https://warehouse.internal/");
    assert_eq!(s.workers, 8);

    let s = svc_loader()
        .env([("APP_API_KEY", "k"), ("APP_PROFILE", "staging")])
        .load()
        .unwrap();
    assert_eq!(s.profile, "staging");
    assert_eq!(
        s.warehouse_api.as_str(),
        "https://warehouse.staging.internal/"
    );
    assert_eq!(s.workers, 2);

    let s = svc_loader()
        .env([
            ("APP_API_KEY", "k"),
            ("APP_PROFILE", "staging"),
            ("APP_WORKERS", "3"),
        ])
        .load()
        .unwrap();
    assert_eq!(
        s.workers, 3,
        "the platform's variables override file values"
    );

    // A profile with no file makes the platform responsible.
    let err = svc_loader()
        .env([("APP_API_KEY", "k"), ("APP_PROFILE", "dev")])
        .load()
        .unwrap_err();
    assert_eq!(
        err.violations()
            .iter()
            .map(|v| (v.input.as_str(), v.code))
            .collect::<Vec<_>>(),
        [("APP_WAREHOUSE_API", Code::MissingRequired)]
    );
}

#[test]
fn bad_file_values_fail_export_and_load() {
    let toml = "[default]\nworkers = 0\n[production]\nwarehouse_api = \"http://plain\"\n";
    let loader = || {
        docuconf::Loader::<Svc>::new()
            .figment(Figment::from(Toml::string(toml).nested()))
            .profiles("APP_PROFILE", "production")
            .termination_log(false)
    };
    let err = loader().export(&Meta::new("svc")).unwrap_err();
    let all = err.problems.join("\n");
    assert!(
        all.contains(
            "APP_WORKERS (Svc.workers): config file value (profile default) 0 is below min 1"
        ),
        "{all}"
    );
    assert!(all.contains("APP_WAREHOUSE_API (Svc.warehouse_api): config file value (profile production) \"http://plain\" has scheme http"), "{all}");

    let err = loader().env([("APP_API_KEY", "k")]).load().unwrap_err();
    let mut codes: Vec<_> = err
        .violations()
        .iter()
        .map(|v| (v.input.as_str(), v.code))
        .collect();
    codes.sort();
    assert_eq!(
        codes,
        [
            ("APP_WAREHOUSE_API", Code::InvalidScheme),
            ("APP_WORKERS", Code::OutOfRange)
        ]
    );
}

#[test]
fn secrets_must_not_be_in_config_files() {
    let toml = "[default]\napi_key = \"sk_live_123\"\nwarehouse_api = \"https://w\"\n";
    let err = docuconf::Loader::<Svc>::new()
        .figment(Figment::from(Toml::string(toml).nested()))
        .profiles("APP_PROFILE", "production")
        .export(&Meta::new("svc"))
        .unwrap_err();
    let all = err.problems.join("\n");
    assert!(
        all.contains("APP_API_KEY (Svc.api_key): a secret must not have a value in a config file"),
        "{all}"
    );
    assert!(!all.contains("sk_live_123"));
}

#[test]
fn profiles_need_a_selector() {
    let err = docuconf::Loader::<Svc>::new()
        .figment(Figment::from(Toml::string(APP_TOML).nested()))
        .export(&Meta::new("svc"))
        .unwrap_err();
    assert!(err.to_string().contains("call Loader::profiles"), "{err}");

    let err = docuconf::Loader::<Svc>::new()
        .figment(Figment::from(Toml::string(APP_TOML).nested()))
        .profiles("PROFILE", "production")
        .export(&Meta::new("svc"))
        .unwrap_err();
    assert!(
        err.to_string()
            .contains("profile selector PROFILE must be a declared variable"),
        "{err}"
    );
}

#[test]
fn global_values_override_every_profile() {
    let toml = "[global]\nworkers = 6\n[staging]\nworkers = 2\nwarehouse_api = \"https://s\"\n";
    let loader = || {
        docuconf::Loader::<Svc>::new()
            .figment(Figment::from(Toml::string(toml).nested()))
            .profiles("APP_PROFILE", "production")
            .termination_log(false)
    };
    let out = loader().export(&Meta::new("svc")).unwrap();
    assert!(out.contains("default:     6"), "{out}");
    assert!(!out.contains("APP_WORKERS:       2"), "{out}");
    let s = loader()
        .env([("APP_API_KEY", "k"), ("APP_PROFILE", "staging")])
        .load()
        .unwrap();
    assert_eq!(s.workers, 6, "as figment does, and as the contract says");
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[allow(dead_code)]
struct RunLimits {
    max: u32,
}

#[test]
fn length_limits_on_urls_json_and_list_items_are_exported() {
    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Lengths {
        /// Where to report the run, PIC X(40).
        #[docuconf(
            schemes = "https",
            max_length = 40,
            default = "https://ledger.example.com/runs/callback"
        )]
        callback_url: String,
        /// A typed URL, PIC X(30).
        #[docuconf(max_length = 30)]
        db_url: Option<Url>,
        /// Run limits as JSON, PIC X(16).
        #[docuconf(max_length = 16, default = r#"{"max":12345678}"#)]
        limits: docuconf::Json<RunLimits>,
        /// Branch codes, OCCURS 1 TO 8 of PIC X(4).
        #[docuconf(min_items = 1, max_items = 8, item_min_length = 2, item_max_length = 4, default = ["ZÜ01", "BE", "GE02"])]
        branches: Vec<String>,
    }
    let out = docuconf::export::<Lengths>(&Meta::new("lengths")).unwrap();
    let block = |name: &str| {
        let start = out.find(&format!("\t\t{name}: {{")).unwrap();
        let end = start + out[start..].find("\n\t\t}").unwrap();
        // Field alignment depends on the neighbours, so compare words.
        out[start..end]
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ")
    };
    assert!(block("CALLBACK_URL").contains("maxLength: 40"), "{out}");
    assert!(block("DB_URL").contains("maxLength: 30"), "{out}");
    assert!(block("LIMITS").contains("maxLength: 16"), "{out}");
    let b = block("BRANCHES");
    assert!(
        b.contains("itemMinLength: 2") && b.contains("itemMaxLength: 4"),
        "{out}"
    );
    if let Some(res) = cue_vet(&out) {
        res.unwrap_or_else(|e| panic!("cue vet failed:\n{e}\n{out}"));
        // The meta-schema checks the new fields: item lengths on an int
        // list are rejected.
        let bad = out
            .replace("default: [\"ZÜ01\", \"BE\", \"GE02\"]", "default: [1]")
            .replace("items:         \"string\"", "items:         \"int\"");
        assert_ne!(bad, out);
        assert!(cue_vet(&bad).unwrap().is_err());
    }
}

#[test]
fn length_limit_declaration_errors() {
    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Bad {
        /// Item lengths only apply to string lists.
        #[docuconf(item_max_length = 5)]
        ports: Vec<u16>,
        /// Item lengths are not for a plain string.
        #[docuconf(item_min_length = 1)]
        name: String,
        /// maxLength does not apply to a bool.
        #[docuconf(max_length = 5)]
        flag: bool,
        /// Item lengths must leave a range.
        #[docuconf(item_min_length = 5, item_max_length = 4)]
        codes: Vec<String>,
        /// String lengths must leave a range.
        #[docuconf(min_length = 5, max_length = 4)]
        label: String,
        /// A default URL longer than maxLength.
        #[docuconf(max_length = 10, default = "https://example.com")]
        site: Url,
        /// A default list item longer than itemMaxLength, in characters.
        #[docuconf(item_max_length = 4, default = ["BE", "ZÜRICH"])]
        branches: Vec<String>,
        /// A default list item shorter than itemMinLength.
        #[docuconf(item_min_length = 2, default = ["B"])]
        regions: Vec<String>,
        /// A default JSON value longer than maxLength once compact.
        #[docuconf(max_length = 16, default = r#"{"max":123456789}"#)]
        limits: docuconf::Json<RunLimits>,
    }
    let err = docuconf::check_declaration::<Bad>().unwrap_err();
    let all = err.problems.join("\n");
    for want in [
        "PORTS (Bad.ports): attribute `item_max_length` does not apply to a list of ints variable",
        "NAME (Bad.name): attribute `item_min_length` does not apply to a string variable",
        "FLAG (Bad.flag): attribute `max_length` does not apply to a bool variable",
        "CODES (Bad.codes): item_min_length 5 is above item_max_length 4",
        "LABEL (Bad.label): min_length 5 is above max_length 4",
        "SITE (Bad.site): default \"https://example.com\" is 19 characters, above maxLength 10",
        "BRANCHES (Bad.branches): default [\"BE\",\"ZÜRICH\"] has item 1 \"ZÜRICH\" of 6 characters, above itemMaxLength 4",
        "REGIONS (Bad.regions): default [\"B\"] has item 0 \"B\" of 1 characters, below itemMinLength 2",
        "LIMITS (Bad.limits): default {\"max\":123456789} is 17 characters of JSON, above maxLength 16",
    ] {
        assert!(all.contains(want), "missing {want:?} in\n{all}");
    }
}
