//! Boot-time checks of file inputs, with certificates generated by rcgen.

mod common;

use common::{ca, days, keystore_bytes, leaf, leaf_with, now, World};
use docuconf::{Code, Docuconf, Error, TlsKeyPair};
use serde::Deserialize;

fn codes(w: &World, input: &str) -> Vec<Code> {
    match w.load() {
        Err(Error::Validation(v)) => v.codes_for(input),
        Err(e) => panic!("{e}"),
        Ok(_) => vec![],
    }
}

fn codes_at(w: &World, input: &str, at: std::time::SystemTime) -> Vec<Code> {
    match w.loader::<common::Gateway>().now(at).load() {
        Err(Error::Validation(v)) => v.codes_for(input),
        Err(e) => panic!("{e}"),
        Ok(_) => vec![],
    }
}

#[test]
fn valid_tls_key_pair() {
    let w = World::new();
    let g = w.load().unwrap();
    assert!(g.serving_tls.dir().ends_with("etc/gateway/tls"));
    assert!(matches!(
        g.serving_tls.private_key(),
        rustls_pki_types::PrivateKeyDer::Pkcs8(_)
    ));
}

#[test]
fn expiring_certificate() {
    // Valid until 2027-01-01; 12 days left is less than minRemaining 720h.
    let w = World::new();
    let at = common::now() + days(200);
    assert_eq!(codes_at(&w, "serving-tls", at), [Code::CertificateExpiring]);
}

#[test]
fn expired_and_not_yet_valid_certificates() {
    let w = World::new();
    assert_eq!(
        codes_at(&w, "serving-tls", now() + days(400)),
        [Code::CertificateInvalid]
    );
    assert_eq!(
        codes_at(&w, "serving-tls", now() - days(365)),
        [Code::CertificateInvalid]
    );
}

#[test]
fn dns_name_mismatch() {
    let w = World::new();
    w.write_tls(&leaf(&["gateway.internal", "www.example.com"], None));
    let err = w.load().unwrap_err();
    assert_eq!(
        err.violations()
            .iter()
            .map(|v| (v.code, v.message.as_str()))
            .collect::<Vec<_>>(),
        [(
            Code::CertificateNameMismatch,
            "certificate does not cover api.example.com"
        )]
    );
}

#[test]
fn wildcard_covers_one_label() {
    let w = World::new();
    w.write_tls(&leaf(&["gateway.internal", "*.example.com"], None));
    w.load().unwrap();

    #[derive(Debug, Deserialize, Docuconf)]
    #[allow(dead_code)]
    struct Deep {
        /// Serving certificate.
        #[docuconf(path = "/etc/gateway/tls", dns_names("a.b.example.com"))]
        tls: TlsKeyPair,
    }
    let err = w.loader::<Deep>().load().unwrap_err();
    assert!(err.has(Code::CertificateNameMismatch), "{err}");
}

#[test]
fn key_mismatch() {
    let w = World::new();
    let a = leaf(&["gateway.internal", "api.example.com"], None);
    let b = leaf(&["gateway.internal", "api.example.com"], None);
    w.write("/etc/gateway/tls/tls.crt", a.cert_pem.as_bytes());
    w.write("/etc/gateway/tls/tls.key", b.key_pem.as_bytes());
    assert_eq!(codes(&w, "serving-tls"), [Code::KeyMismatch]);
}

#[test]
fn malformed_key_and_certificate() {
    let w = World::new();
    w.write("/etc/gateway/tls/tls.key", b"not a key");
    assert_eq!(codes(&w, "serving-tls"), [Code::FileMalformed]);

    let w = World::new();
    w.write("/etc/gateway/tls/tls.crt", b"no pem here");
    assert_eq!(codes(&w, "serving-tls"), [Code::CertificateInvalid]);
}

#[test]
fn disallowed_key_algorithm() {
    let w = World::new();
    let key = rcgen::KeyPair::generate_for(&rcgen::PKCS_ED25519).unwrap();
    w.write_tls(&leaf_with(
        &["gateway.internal", "api.example.com"],
        None,
        key,
    ));
    let err = w.load().unwrap_err();
    assert_eq!(err.violations().len(), 1, "{err}");
    assert_eq!(err.violations()[0].code, Code::CertificateInvalid);
    assert!(
        err.to_string().contains("Ed25519 is not one of ECDSA, RSA"),
        "{err}"
    );
}

#[derive(Debug, Deserialize, Docuconf)]
struct Mtls {
    /// Serving certificate, issued by our CA.
    #[docuconf(path = "/etc/gateway/tls", require_ca)]
    tls: TlsKeyPair,
}

#[test]
fn chain_to_ca() {
    let w = World::new();
    w.write("/etc/gateway/tls/ca.crt", w.ca.pem.as_bytes());
    let m = w.loader::<Mtls>().load().unwrap();
    assert_eq!(m.tls.ca_certificates().len(), 1);

    let other = ca("Other CA");
    w.write("/etc/gateway/tls/ca.crt", other.pem.as_bytes());
    let err = w.loader::<Mtls>().load().unwrap_err();
    assert!(err.has(Code::CertificateInvalid), "{err}");
    assert!(
        err.to_string().contains("does not chain to ca.crt"),
        "{err}"
    );

    w.remove("/etc/gateway/tls/ca.crt");
    let err = w.loader::<Mtls>().load().unwrap_err();
    assert!(err.has(Code::FileMissing), "{err}");
}

#[test]
fn missing_required_file_and_absent_optional_file() {
    let w = World::new();
    w.remove("/etc/gateway/license/license.key");
    w.remove("/data/geoip/GeoLite2-City.mmdb");
    let err = w.load().unwrap_err();
    assert_eq!(err.violations().len(), 1, "{err}");
    assert_eq!(err.violations()[0].input, "license");
    assert_eq!(err.violations()[0].code, Code::FileMissing);

    let w = World::new();
    std::fs::remove_dir_all(w.path("/etc/gateway/tls")).unwrap();
    assert_eq!(codes(&w, "serving-tls"), [Code::FileMissing]);

    let w = World::new();
    w.remove("/data/geoip/GeoLite2-City.mmdb");
    assert!(w.load().unwrap().geoip.is_none());
}

#[test]
fn malformed_config_file() {
    let w = World::new();
    w.write("/etc/gateway/routes/routes.yaml", b"routes: [unclosed");
    assert_eq!(codes(&w, "routes"), [Code::FileMalformed]);
}

#[test]
fn config_file_schema_violation() {
    let w = World::new();
    w.write(
        "/etc/gateway/routes/routes.yaml",
        b"routes:\n  - match: api\n    upstream: ftp://x\n",
    );
    let err = w.load().unwrap_err();
    let v = err.violations();
    assert!(
        v.iter()
            .all(|x| x.code == Code::SchemaMismatch && x.input == "routes"),
        "{err}"
    );
    assert_eq!(v.len(), 2, "{err}");
    assert!(err.to_string().contains("/routes/0/match"), "{err}");

    w.write("/etc/gateway/routes/routes.yaml", b"routes: []\n");
    assert_eq!(codes(&w, "routes"), [Code::SchemaMismatch]);
    w.write(
        "/etc/gateway/routes/routes.yaml",
        b"routes:\n  - {match: /, upstream: http://x}\nextra: 1\n",
    );
    assert_eq!(codes(&w, "routes"), [Code::SchemaMismatch]);
}

#[test]
fn config_file_with_bom_and_path_env() {
    let mut w = World::new();
    let mut json = b"\xEF\xBB\xBF".to_vec();
    json.extend_from_slice(br#"{"routes":[{"match":"/v2","upstream":"http://v2"}]}"#);
    // ROUTES_FILE moves the file; DOCUCONF_FILE_ROOT still applies.
    w.write("/srv/routes/alt.yaml", &json);
    w.set("ROUTES_FILE", "/srv/routes/alt.yaml");
    let g = w.load().unwrap();
    assert_eq!(g.routes.routes[0].r#match, "/v2");
    assert!(g.routes.path().ends_with("srv/routes/alt.yaml"));
}

#[test]
fn file_too_large() {
    let w = World::new();
    w.write("/etc/gateway/routes/routes.yaml", &vec![b'#'; 65537]);
    assert_eq!(codes(&w, "routes"), [Code::FileTooLarge]);
}

#[test]
fn unreadable_file() {
    let w = World::new();
    w.remove("/etc/gateway/license/license.key");
    std::fs::create_dir_all(w.path("/etc/gateway/license/license.key")).unwrap();
    assert_eq!(codes(&w, "license"), [Code::FileUnreadable]);
}

#[test]
fn text_file_constraints() {
    let w = World::new();
    w.write("/etc/gateway/license/license.key", b"not-a-licence");
    assert_eq!(codes(&w, "license"), [Code::PatternMismatch]);
    w.write("/etc/gateway/license/license.key", b"\xff\xfe");
    assert_eq!(codes(&w, "license"), [Code::FileMalformed]);
}

#[test]
fn ca_bundle() {
    let w = World::new();
    w.write("/etc/gateway/ca/bundle.pem", b"nothing here");
    assert_eq!(codes(&w, "upstream-ca"), [Code::FileMalformed]);

    #[derive(Debug, Deserialize, Docuconf)]
    struct Two {
        /// Two CAs we trust.
        #[docuconf(path = "/etc/gateway/ca/bundle.pem", min_certificates = 2)]
        cas: docuconf::CaBundle,
    }
    let w = World::new();
    let err = w.loader::<Two>().load().unwrap_err();
    assert!(err.has(Code::FileMalformed), "{err}");
    assert!(
        err.to_string()
            .contains("holds 1 certificate, need at least 2"),
        "{err}"
    );
    let both = format!("{}{}", w.ca.pem, ca("Second").pem);
    w.write("/etc/gateway/ca/bundle.pem", both.as_bytes());
    assert_eq!(
        w.loader::<Two>().load().unwrap().cas.certificates().len(),
        2
    );
}

#[test]
fn keystore() {
    let mut w = World::new();
    w.set("PARTNER_KEYSTORE_PASSWORD", "wrong");
    let err = w.load().unwrap_err();
    assert_eq!(err.violations().len(), 1, "{err}");
    assert_eq!(err.violations()[0].code, Code::KeystoreUnreadable);
    assert!(!err.to_string().contains("wrong"), "{err}");

    let w = World::new();
    w.write("/etc/gateway/partner/keystore.p12", b"garbage");
    assert_eq!(codes(&w, "partner-keystore"), [Code::KeystoreUnreadable]);

    let w = World::new();
    let partner = leaf(&["partner-client"], None);
    w.write(
        "/etc/gateway/partner/keystore.p12",
        &keystore_bytes(&partner, "s3cret-pass"),
    );
    let ks = w.load().unwrap().partner_keystore.unwrap();
    assert_eq!(ks.cert_chain()[0].as_ref(), partner.cert_der.as_slice());
    assert_eq!(
        codes_at(&w, "partner-keystore", now() + days(400)),
        [Code::CertificateInvalid]
    );
}

#[test]
fn file_inputs_cannot_be_deserialized_directly() {
    let err = serde_json::from_str::<TlsKeyPair>("\"x\"").unwrap_err();
    assert!(err.to_string().contains("docuconf::load"), "{err}");
}
