// Code generated by docuconf. DO NOT EDIT.
package gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "gateway"
		generator: {
			language: "rust"
			sdk:      "docuconf"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			required:    true
			examples: ["https://app.example.com"]
			items:    "string"
			encoding: "json"
			minItems: 1
		}
		CACHE__SIZE: {
			type:        "int"
			description: "Maximum cached entries"
			default:     1000
			min:         0
			max:         4294967295
		}
		CACHE__TTL: {
			type:        "duration"
			description: "Cache entry lifetime"
			default:     "5m"
			encoding:    "go"
		}
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		DEBUG: {
			type:        "bool"
			description: "Serve the debug endpoints"
			default:     false
		}
		EXTRA_PORTS: {
			type:        "list"
			description: "Extra ports to listen on"
			items:       "int"
			encoding:    "json"
			maxItems:    4
			itemMin:     1
			itemMax:     65535
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			default:     "info"
			group:       "logging"
			values: ["debug", "info", "warn", "error"]
		}
		MEMORY_LIMIT: {
			type:        "int"
			description: "Soft memory limit, in bytes"
			min:         1
		}
		METRICS_TOKEN: {
			type:        "string"
			description: "API token for the metrics backend"
			secret:      true
			minLength:   20
		}
		PARTNER_KEYSTORE_PASSWORD: {
			type:        "string"
			description: "Password for the partner mTLS keystore"
			required:    true
			secret:      true
		}
		POD_NAMESPACE: {
			type:        "string"
			description: "Namespace the gateway runs in, for metrics labels"
			required:    true
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			default:     8080
			min:         1
			max:         65535
		}
		RATE_LIMITS: {
			type:        "json"
			description: "Default per-client rate limits"
			default: {
				perMinute: 60
			}
			schema: {
				"$schema":            "https://json-schema.org/draft/2020-12/schema"
				additionalProperties: false
				description:          "Bounds each client's request rate."
				properties: {
					burst: {
						default:     null
						description: "Extra requests allowed in a burst."
						format:      "uint32"
						minimum:     0
						type: ["integer", "null"]
					}
					perMinute: {
						description: "Requests allowed per minute."
						format:      "uint32"
						minimum:     1
						type:        "integer"
					}
				}
				required: ["perMinute"]
				title: "RateLimits"
				type:  "object"
			}
		}
		REGION: {
			type:        "string"
			description: "Cloud region, such as eu-west-1"
			deprecated: {
				message: "Read from the node's topology labels instead"
			}
			minLength: 4
			maxLength: 32
			pattern:   "^[a-z]{2}-[a-z]+-[0-9]$"
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Upstream request timeout"
			default:     "30s"
			encoding:    "go"
			min:         "1s"
			max:         "5m"
		}
		SHARDS: {
			type:        "list"
			description: "Shard ids this instance owns"
			items:       "int"
			encoding:    "json"
			itemMin:     0
			itemMax:     1023
		}
		STRIPE_API_BASE: {
			type:        "url"
			description: "Stripe API base URL"
			default:     "https://api.stripe.com"
			schemes: ["https"]
		}
		TRACE_SAMPLE_RATIO: {
			type:        "float"
			description: "Fraction of requests traced"
			default:     0.1
			min:         0.0
			max:         1.0
		}
	}
	files: {
		geoip: {
			type:        "binary"
			description: "GeoIP database for country-based routing"
			path:        "/data/geoip/GeoLite2-City.mmdb"
			maxSize:     134217728
		}
		license: {
			type:        "text"
			description: "Gateway licence key"
			required:    true
			path:        "/etc/gateway/license/license.key"
			pattern:     "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		"partner-keystore": {
			type:        "keystore"
			format:      "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			path:        "/etc/gateway/partner/keystore.p12"
			passwordVar: "PARTNER_KEYSTORE_PASSWORD"
		}
		routes: {
			type:        "config"
			format:      "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required:    true
			path:        "/etc/gateway/routes/routes.yaml"
			pathEnv:     "ROUTES_FILE"
			maxSize:     65536
			schema: {
				"$defs": {
					Route: {
						additionalProperties: false
						description:          "Sends requests under a path prefix to an upstream."
						properties: {
							match: {
								description: "Path prefix the route matches."
								pattern:     "^/"
								type:        "string"
							}
							timeout: {
								default:     null
								description: "Per-request timeout, such as 5s."
								type: ["string", "null"]
							}
							upstream: {
								description: "Upstream base URL."
								pattern:     "^https?://"
								type:        "string"
							}
						}
						required: ["match", "upstream"]
						type: "object"
					}
				}
				"$schema":            "https://json-schema.org/draft/2020-12/schema"
				additionalProperties: false
				description:          "The gateway's routing table file."
				properties: {
					routes: {
						description: "Routes in match order."
						items: {
							"$ref": "#/$defs/Route"
						}
						minItems: 1
						type:     "array"
					}
				}
				required: ["routes"]
				title: "Routes"
				type:  "object"
			}
		}
		"serving-tls": {
			type:        "tls"
			description: "Certificate the gateway serves HTTPS with"
			required:    true
			path:        "/etc/gateway/tls"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
		}
		"upstream-ca": {
			type:        "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path:        "/etc/gateway/ca/bundle.pem"
			pathEnv:     "SSL_CERT_FILE"
		}
	}
}
